// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBy71yFu0-AqbIqLTK30wz0dsTWirx_sqc',
    appId: '1:388241005590:web:5af235f4893a4da4fb2937',
    messagingSenderId: '388241005590',
    projectId: 'tasky-app-8d9d7',
    authDomain: 'tasky-app-8d9d7.firebaseapp.com',
    storageBucket: 'tasky-app-8d9d7.firebasestorage.app',
    measurementId: 'G-ZGYCG724EV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoH-JMz1FnpZx1zGP5I-SIejbGi2PN20Y',
    appId: '1:388241005590:android:7ed777dd81c2e62bfb2937',
    messagingSenderId: '388241005590',
    projectId: 'tasky-app-8d9d7',
    storageBucket: 'tasky-app-8d9d7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACUVesWNMqKaKR7xHLDFcAquNtdbDw1r8',
    appId: '1:388241005590:ios:bc26be781a6b7c65fb2937',
    messagingSenderId: '388241005590',
    projectId: 'tasky-app-8d9d7',
    storageBucket: 'tasky-app-8d9d7.firebasestorage.app',
    iosBundleId: 'com.example.taskyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBy71yFu0-AqbIqLTK30wz0dsTWirx_sqc',
    appId: '1:388241005590:web:dd0b33fca55e65ddfb2937',
    messagingSenderId: '388241005590',
    projectId: 'tasky-app-8d9d7',
    authDomain: 'tasky-app-8d9d7.firebaseapp.com',
    storageBucket: 'tasky-app-8d9d7.firebasestorage.app',
    measurementId: 'G-SS0K3XJP1S',
  );
}
